name = "image-bg-remover"
main = ".open-next/worker.js"
compatibility_date = "2026-03-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_id = "05eba51a-c623-4606-bbfd-a51fce1e268f"

[vars]
REMOVE_BG_API_KEY = "9qJZKxQ9vuLRRUKUBSRktqMk"
