name = "image-bg-remover-worker"
main = "index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "image-bg-remover-users"
database_id = "05eba51a-c623-4606-bbfd-a51fce1e268f"

# Environment variables
[vars]
